### ISSUE TITLE
Issue with adding two "NIC_Basic" to one node.

### ISSUE THREAD

**Issue by 842Mono** [fabric-testbed/fabrictestbed-extensions#14]
I cannot add two "NIC_Basic" components to one node. I get `Slice Fail: list index out of range`. Not sure if the issue is with fablib or with the base library.

Code to try:

    try:
        #Create Slice
        slice1 = fablib.new_slice(name=slice_name)

    
        #nodes
        n1 = slice1.add_node(name=node1_name, site=site)
        n1.set_capacities(cores=other_cores, ram=other_ram, disk=other_disk)
        n1.set_image(image)

        scheduler_nic1 = n1.add_component(model='NIC_Basic', name="nic1")
        scheduler_nic2 = n1.add_component(model='NIC_Basic', name="nic2")

        #Submit Slice Request
        slice1.submit(wait_progress=True)
    except Exception as e:
        print(f"Slice Fail: {e}")
        traceback.print_exc()

Error:

    Slice Fail: list index out of range
    Traceback (most recent call last):
      File "/tmp/ipykernel_272480/1309156764.py", line 15, in <module>
        slice1.submit(wait_progress=True)
      File "/home/mono/Sachen/Work/FABRIC/fabric_python_api_locally/venv1/lib/python3.9/site- packages/fabrictestbed_extensions/fablib/slice.py", line 381, in submit
        self.update_slice()
      File "/home/mono/Sachen/Work/FABRIC/fabric_python_api_locally/venv1/lib/python3.9/site-packages/fabrictestbed_extensions/fablib/slice.py", line 102, in update_slice
        self.sm_slice = list(filter(lambda x: x.slice_name == self.slice_name, slices))[0]
    IndexError: list index out of range

**Comment by paul-ruth** [comment]
I think this is done be need to test
