### ISSUE TITLE
`slice.show()` can crash

### ISSUE THREAD

**Issue by sajith** [fabric-testbed/fabrictestbed-extensions#195]
If we try to `show()` a slice before `submit()`, we crash.  Consider the below snippet:

```python
from fabrictestbed_extensions.fablib.fablib import FablibManager

fm = FablibManager()
slice = fm.new_slice(name="test-slice")
slice.show()
```

This fails with:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./fabrictestbed_extensions/fablib/slice.py", line 168, in show
    data = self.toDict()
           ^^^^^^^^^^^^^
  File "./fabrictestbed_extensions/fablib/slice.py", line 486, in toDict
    "project_id": str(self.get_project_id()),
                      ^^^^^^^^^^^^^^^^^^^^^
  File "./fabrictestbed_extensions/fablib/slice.py", line 842, in get_project_id
    return self.sm_slice.project_id
           ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'project_id'
```

Perhaps this could fail a little more gracefully.

**Comment by kthare10** [comment]
Addressed in version `2.0.3`
