### ISSUE TITLE
Unhappy `Slice.delete()`

### ISSUE THREAD

**Issue by sajith** [fabric-testbed/fabrictestbed-extensions#196]
While working on PR #187, I came across a backtrace from `Slice.delete()`:

```
Exception ignored in: <function ApiClient.__del__ at 0x7f03d0c1dee0>
Traceback (most recent call last):
  File "./venv/lib/python3.11/site-packages/fabric_cf/orchestrator/swagger_client/api_client.py", line 78, in __del__
    self.pool.close()
  File "/usr/lib/python3.11/multiprocessing/pool.py", line 652, in close
    self._change_notifier.put(None)
  File "/usr/lib/python3.11/multiprocessing/queues.py", line 377, in put
    self._writer.send_bytes(obj)
  File "/usr/lib/python3.11/multiprocessing/connection.py", line 199, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.11/multiprocessing/connection.py", line 410, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.11/multiprocessing/connection.py", line 367, in _send
    n = write(self._handle, buf)
        ^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 9] Bad file descriptor
Exception ignored in: <function ApiClient.__del__ at 0x7f03bd7a8e00>
Traceback (most recent call last):
  File "./venv/lib/python3.11/site-packages/fabric_cm/credmgr/swagger_client/api_client.py", line 78, in __del__
    self.pool.close()
  File "/usr/lib/python3.11/multiprocessing/pool.py", line 652, in close
    self._change_notifier.put(None)
  File "/usr/lib/python3.11/multiprocessing/queues.py", line 377, in put
    self._writer.send_bytes(obj)
  File "/usr/lib/python3.11/multiprocessing/connection.py", line 199, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.11/multiprocessing/connection.py", line 410, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.11/multiprocessing/connection.py", line 367, in _send
    n = write(self._handle, buf)
        ^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 9] Bad file descriptor
```

To reproduce, try: `python tests/integration/test_hello_fabric.py`

**Comment by kthare10** [comment]
This is an issue in fabric-orchestrator-client in the swagger generated code. I will fix this in the underlying packages `fabric-credmgr-client` and `fabric-orchestrator-client` and update dependencies in fablib accordingly.

**Comment by sajith** [comment]
@kthare10 Thank you!  The backtrace seems to suggest that it is a problem somewhere in API client code, but I suspect fablib also is mishandling something. Consider this code:

```python
from fabrictestbed_extensions.fablib.fablib import FablibManager

fm = FablibManager()
slice = fm.new_slice(name="test-slice")

try:
    slice.add_node(name="test-node")
    slice.submit()
    slice.show()
finally:
    slice.delete() 
```
 
This will produce a backtrace, but will work normally if that `slice.show()` is removed. I do not understand why.

**Comment by kthare10** [comment]
I think these two are unrelated. I have observed the above exception when I directly use the base library without fablib. The issue is with all the APIs, in which a bigger payload is returned, sometimes, the underlying `connexion` library isn't able to cleanup the underlying tcp connection which lingers on and hence the process pool used by `connexion` library fails to close all the open processes gracefully. This is a quick fix for now to unblock fablib. But I would look for a better fix to address the underlying issue of lingering connections.

**Comment by sajith** [comment]
There's a different error now:

```
Exception ignored in: <function ApiClient.__del__ at 0x7fae891c0fe0>
Traceback (most recent call last):
  File "[...]/fabrictestbed-extensions/.tox/integration/lib/python3.11/site-packages/fabric_cm/credmgr/swagger_client/api_client.py", line 82, in __del__
    logging.getLogger().error(f"Ignoring connexion pool error: {e}")
    ^^^^^^^
NameError: name 'logging' is not defined
```

**Comment by kthare10** [comment]
Could you please try again with `fabrictestbed==1.5.3` in pyproject.toml

**Comment by sajith** [comment]
@kthare10  I did , and that worked. Thank you!
