### ISSUE TITLE
list_facility_ports cannot serialize to json

### ISSUE THREAD

**Issue by disprosium8** [fabric-testbed/fabrictestbed-extensions#210]
I fixed this locally with `"link_layer": str(link.layer)` at:

https://github.com/fabric-testbed/fabrictestbed-extensions/blob/main/fabrictestbed_extensions/fablib/resources.py#L1014

```
from fabrictestbed_extensions.fablib.fablib import FablibManager as fablib_manager                                                                                                  
fablib = fablib_manager()                                                                                                                                                           
fablib.show_config()                                                                                                                                                                
fablib.list_facility_ports(output='json') 

Traceback (most recent call last):
  File "/home/ezra/test_fp.py", line 7, in <module>
    fablib.list_facility_ports(output='json')
  File "/home/ezra/repos/fabrictestbed-extensions/fabrictestbed_extensions/fablib/fablib.py", line 1160, in list_facility_ports
    return self.get_facility_ports(update=update).list_facility_ports(
  File "/home/ezra/repos/fabrictestbed-extensions/fabrictestbed_extensions/fablib/resources.py", line 1043, in list_facility_ports
    return self.get_fablib_manager().list_table(
  File "/home/ezra/repos/fabrictestbed-extensions/fabrictestbed_extensions/fablib/fablib.py", line 2277, in list_table
    return self.list_table_json(data, quiet=quiet)
  File "/home/ezra/repos/fabrictestbed-extensions/fabrictestbed_extensions/fablib/fablib.py", line 2224, in list_table_json
    json_str = json.dumps(data, indent=4)
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.9/json/encoder.py", line 429, in _iterencode
    yield from _iterencode_list(o, _current_indent_level)
  File "/usr/lib/python3.9/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.9/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.9/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type NSLayer is not JSON serializable
```

**Comment by disprosium8** [comment]
@kthare10 as a follow-up to this, how is the facility port information added to FIM? For the fabfed work, we are looking to get the raw values as maintained here: https://github.com/fabric-testbed/NetworkController/blob/main/device-config/ansible/inventory/fabric-cisco-dev.py#L281

It looks like most of that is there, although we would need some parsing info for node_id and name fields and a way to get the associated site (e.g. STAR, UTAH, etc.)

**Comment by kthare10** [comment]
@disprosium8 - Looking at this will keep you posted.
