### ISSUE TITLE
Error from readthedocs.org

### ISSUE THREAD

**Issue by sajith** [fabric-testbed/fabrictestbed-extensions#234]
There's a new error from readthedocs:

```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/fabric-fablib/envs/233/lib/python3.9/site-packages/sphinx/cmd/build.py", line 285, in build_main
    app.build(args.force_all, args.filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/fabric-fablib/envs/233/lib/python3.9/site-packages/sphinx/application.py", line 353, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/fabric-fablib/envs/233/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 311, in build_update
    self.build(to_build,
  File "/home/docs/checkouts/readthedocs.org/user_builds/fabric-fablib/envs/233/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 378, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/docs/checkouts/readthedocs.org/user_builds/fabric-fablib/envs/233/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 586, in write
    self._write_serial(sorted(docnames))
  File "/home/docs/checkouts/readthedocs.org/user_builds/fabric-fablib/envs/233/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 596, in _write_serial
    self.write_doc(docname, doctree)
  File "/home/docs/checkouts/readthedocs.org/user_builds/fabric-fablib/envs/233/lib/python3.9/site-packages/sphinx/builders/html/__init__.py", line 672, in write_doc
    self.handle_page(docname, ctx, event_arg=doctree)
  File "/home/docs/checkouts/readthedocs.org/user_builds/fabric-fablib/envs/233/lib/python3.9/site-packages/sphinx/builders/html/__init__.py", line 1076, in handle_page
    newtmpl = self.app.emit_firstresult('html-page-context', pagename,
  File "/home/docs/checkouts/readthedocs.org/user_builds/fabric-fablib/envs/233/lib/python3.9/site-packages/sphinx/application.py", line 481, in emit_firstresult
    return self.events.emit_firstresult(event, *args,
  File "/home/docs/checkouts/readthedocs.org/user_builds/fabric-fablib/envs/233/lib/python3.9/site-packages/sphinx/events.py", line 117, in emit_firstresult
    for result in self.emit(name, *args, allowed_exceptions=allowed_exceptions):
  File "/home/docs/checkouts/readthedocs.org/user_builds/fabric-fablib/envs/233/lib/python3.9/site-packages/sphinx/events.py", line 96, in emit
    results.append(listener.handler(self.app, *args))
  File "/home/docs/checkouts/readthedocs.org/user_builds/fabric-fablib/envs/233/lib/python3.9/site-packages/furo/__init__.py", line 179, in _html_page_context
    raise ConfigError(
sphinx.errors.ConfigError: This documentation is not using `furo.css` as the stylesheet. If you have set `html_style` in your conf.py file, remove it.

Configuration error:
This documentation is not using `furo.css` as the stylesheet. If you have set `html_style` in your conf.py file, remove it.
```

It could be that the latest release of furo theme broke something.  I have not been able to reproduce this error locally.

_Originally posted by @sajith in https://github.com/fabric-testbed/fabrictestbed-extensions/issues/233#issuecomment-1686839290_

**Comment by sajith** [comment]
This seems to be a transient error.  The latest builds ([example #1](https://readthedocs.org/projects/fabric-fablib/builds/21675226/), [example #2](https://readthedocs.org/projects/fabric-fablib/builds/21675444/)) were just fine. 

For future reference, https://readthedocs.org/projects/fabric-fablib/builds/21674963/ was the problem build.
